name: 📦 Transform and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: 🪄 Transform
        uses: Design-System-Pro/transform-action@v1.1.1
        with:
          output-path: "./dist"
          tokens-path: "./tokens"

      - name: 🚀 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
