name: 🚀 Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"

      - name: 🪄 Transform
        uses: Design-System-Pro/transform-action@v1.0.4
        with:
          output-path: "./packages/alpha"
          tokens-path: "./"

      - name: 🚀 Release
        uses: Design-System-Pro/release-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dist-dir: "./packages/alpha"
