name: 📦 Transform and Release

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: 🪄 Transform
        uses: Design-System-Pro/transform-action@v1.1.1
        with:
          output-path: "./dist"
          tokens-path: "./tokens"

      - name: 🚀 Release
        uses: Design-System-Pro/release-action@v1.1.0-next.4
        with:
          dist-dir: "./dist"
          registry-url: "https://npm.pkg.github.com"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: '"main", { name: "next", prerelease: true }'
