name: ✨ Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: ✨ Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@tomasfrancisco"

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.SECRET_GITHUB_REGISTRY_TOKEN }}

      - name: Install Dependencies
        run: pnpm install

      - name: Install Dependencies
        run: pnpm build

      - name: Create Release
        uses: changesets/action@v1
        with:
          publish: pnpm release-packages
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_REGISTRY_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.SECRET_GITHUB_REGISTRY_TOKEN }}
